### ISSUE TITLE
User added twice in a stream while doing the connectivity changes.

### ISSUE THREAD

**Issue by aravindhu-gloify** [100mslive/sample-app-android#23]
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/57980609/111437412-12938a00-8729-11eb-8b9b-d2a405f06998.png)

I have joined the meeting room and my device connected with both wifi and mobile network connection.
Then, I turned off my wifi and the connection lost dialog has shown. In that, I selected the retry option. 
After that, I have been added twice to the room.

**Comment by PratimMallick** [comment]
@aravindhu-gloify please check with our latest app. These issues are fixed in our latest release branch `release-v2`
