### ISSUE TITLE
getting error inferred type is HMSPeer but HMSRemotePeer was expected

### ISSUE THREAD

**Issue by rahul-quicksell** [100mslive/sample-app-android#88]
I just tried the sample project. its having releasev2 branch and when i run i get this error:

`sample-app-android/app/src/main/java/live/hms/app2/ui/meeting/MeetingViewModel.kt: (534, 27): Type mismatch: inferred type is HMSPeer but HMSRemotePeer was expected
`

i don't know what wrong have I done.

**Comment by PratimMallick** [comment]
Thanks for pointing it out @rahul-quicksell . We have added the fix, which is updating with the latest version of our SDK (`v2.0.9`) 


Also now the app doesnot need to have a dependancy on webrtc lib

**Comment by AniketSK** [comment]
Thanks @rahul-quicksell ! Just doing a pull on the release-v2 branch will have this up and running again 🙌

**Comment by rahul-quicksell** [comment]
thank you @PratimMallick @AniketSK .

any ETA for the release?

**Comment by AniketSK** [comment]
@rahul-quicksell it has been released! If you do a pull or clone again, you will have the correct code to build.
